<<<<<<< HEAD
```{r}
suppressPackageStartupMessages(library(tidyverse))
#filename <- file.choose("cleaned_h1b_data.rds")
#print(filename)
h1b_country <- 
  read_rds('dataset/cleaned_h1b_data.rds')
```

```{r}
#changing the year to numerical values
current_names <- names(h1b_country)
print(current_names)
#names(df) <- new_names

```


```{r}
colnames(h1b_country) <- c('Country','Continent','1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022') 

h1b_country
```


```{r}
h1b_continent <- h1b_country |>
  group_by(Continent)|>
  select(-Country)|>
  summarize(across(everything(), sum, na.rm = TRUE))

library(tidyr)
data_long <- pivot_longer(h1b_continent, cols = -Continent, names_to = "year", values_to = "count_h1b")

data_long
```


```{r}

```


```{r}
ggplot(data_long, aes(x = year, y = count_h1b, fill = Continent)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "Total Values by Continent Over the Years",
       x = "Year", y = "Total Value") + theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(data_long, aes(x = year, y = count_h1b, fill = Continent)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Continent, scales='free_y') + 
  labs(title = "Total Values by Continent Over the Years",
       x = "Year", y = "Total Value") + theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(guide=guide_axis(check.overlap=TRUE))
```


```{r}
h1b_continent <- h1b_country |>
  filter(Continent == 'Unknown') |>
  select(-Continent)

# library(tidyr)
unknown_longer <- pivot_longer(h1b_continent, cols = -Country, names_to = "year", values_to = "count_h1b")
# 
unknown_longer
```

```{r}
names(unknown_longer)
```


```{r}
clean_un <- unknown_longer |>
  filter(Country == 'United Nations Laissez-Passer')|>
  filter(count_h1b != 0)

clean_un
```
This shows that no one with a nationality designated as 'United Nations Laissez-Passer' has received an h1b visa from the years 1997-2022, so we can clear that.

```{r}
ggplot(unknown_longer, aes(x = year, y = count_h1b, fill = Country)) +
  geom_bar(stat = "identity", position = "stack") +
  #facet_wrap(~Continent, scales='free_y')+
  labs(title = "Total Values by Continent Over the Years",
       x = "Year", y = "Total Value") + theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
library(viridis)
h1b_country_temp <- h1b_country |>
  select(-Continent)

data_long_all <- pivot_longer(h1b_country_temp, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_all <- list()

for(year_iter in unique(data_long_all$year)){
  print(year_iter)
  all_temp <- data_long_all |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- all_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- all_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_all[[year_iter]] <- pie_chart
  
}
print(piecharts_all)
```



```{r}
h1b_africa <- h1b_country |>
  filter(Continent == 'Africa') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_africa <- pivot_longer(h1b_africa, cols=-Country, names_to = "year", values_to = "count_h1b")
```


```{r}
  africa_temp <- data_long_africa |> filter(year == 1997)
  
  #choose top 5
  top_countries <- africa_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- africa_temp |>
  anti_join(top_countries, by = "Country") |>
  filter(!is.na(count_h1b))|>
  summarise(Country = "Other",total_count = sum(count_h1b))
  
  other_countries
```

```{r}

piecharts <- list()
for(year_iter in unique(data_long_africa$year)){
  africa_temp <- data_long_africa |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- africa_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- africa_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 African Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts[[year_iter]] <- pie_chart
  
}
print(piecharts)

```


```{r}
#do the same for other continents

h1b_asia <- h1b_country |>
  filter(Continent == 'Asia') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_asia <- pivot_longer(h1b_asia, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_asia <- list()

for(year_iter in unique(data_long_asia$year)){
  print(year_iter)
  asia_temp <- data_long_asia |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- asia_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- asia_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 Asian Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_asia[[year_iter]] <- pie_chart
  
}
print(piecharts_asia)
```


```{r}

#do the same for other continents
h1b_europe <- h1b_country |>
  filter(Continent == 'Europe') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_europe <- pivot_longer(h1b_europe, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_europe <- list()

for(year_iter in unique(data_long_europe$year)){
  print(year_iter)
  europe_temp <- data_long_europe |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- europe_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- europe_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 European Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_europe[[year_iter]] <- pie_chart
  
}
print(piecharts_europe)
```


```{r}
h1b_namerica <- h1b_country |>
  filter(Continent == 'North America') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_namerica <- pivot_longer(h1b_namerica, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_namerica <- list()

for(year_iter in unique(data_long_namerica$year)){
  print(year_iter)
  namerica_temp <- data_long_namerica |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- namerica_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- namerica_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 North American Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_namerica[[year_iter]] <- pie_chart
  
}
print(piecharts_namerica)
```
```{r}
h1b_samerica <- h1b_country |>
  filter(Continent == 'South America') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_samerica <- pivot_longer(h1b_samerica, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_samerica <- list()

for(year_iter in unique(data_long_samerica$year)){
  print(year_iter)
  samerica_temp <- data_long_samerica |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- samerica_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(5)
  
  #summarise the rest
  other_countries <- samerica_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 South American Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_samerica[[year_iter]] <- pie_chart
  
}
print(piecharts_samerica)
```

```{r}
h1b_oceania <- h1b_country |>
  filter(Continent == 'Oceania') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_oceania <- pivot_longer(h1b_oceania, cols=-Country, names_to = "year", values_to = "count_h1b")

piecharts_oceania <- list()

for(year_iter in unique(data_long_oceania$year)){
  print(year_iter)
  oceania_temp <- data_long_oceania |> filter(year == year_iter)
  
  #choose top 5
  top_countries <- oceania_temp |>
  group_by(Country) |>
  summarise(total_count = count_h1b) |>
  arrange(desc(total_count)) |>
  top_n(3)
  
  #summarise the rest
  other_countries <- oceania_temp |>
  anti_join(top_countries, by = "Country") |>
    filter(!is.na(count_h1b))|>
  summarise(Country = "Other",
            total_count = sum(count_h1b))
  
  combined_data <- bind_rows(top_countries, other_countries)
  pie_chart <- pie(combined_data$total_count, labels = combined_data$Country, main = paste("Top 5 Oceanian Countries in", year_iter), col=viridis(length(combined_data$total_count)))
  
  piecharts_oceania[[year_iter]] <- pie_chart
  
}
print(piecharts_oceania)
```

```{r}
h1b_other <- h1b_country |>
  filter(Continent == 'Unknown') |>
  select(-Continent)
  #summarize(across(where(is.numeric), sum, na.rm = TRUE))

data_long_other <- pivot_longer(h1b_other, cols=-Country, names_to = "year", values_to = "count_h1b")

data_long_other
```



=======
```{r}
# Load libraries and dataset
suppressPackageStartupMessages(library(tidyverse))
h1b_country <- read_rds('dataset/cleaned_h1b_data.rds')
```

```{r}
# Rename year columns
years <- paste0(1997:2022)
colnames(h1b_country) <- c('Country', 'Continent', years)
```

```{r}
# Summarize total H1B visas per year and transform into long format for plotting
total_h1b_by_year_long <- h1b_country %>%
  select(all_of(years)) %>%
  summarise(across(everything(), sum, na.rm = TRUE)) %>%
  pivot_longer(cols = everything(), names_to = "year", values_to = "Total_H1B_Visas")

# Plot total H1B visas issued worldwide over the years
ggplot(total_h1b_by_year_long, aes(x = year, y = Total_H1B_Visas, fill = year)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d() +
  labs(title = "Total H1B Visas Issued Worldwide Over the Years",
       x = "Year", y = "Total Number of H1B Visas") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.position = "none")
```

```{r}
# Summarize data by continent and transform into long format
data_long <- h1b_country %>%
  group_by(Continent) %>%
  summarise(across(all_of(years), sum, na.rm = TRUE)) %>%
  pivot_longer(cols = all_of(years), names_to = "year", values_to = "count_h1b")

# Plot total values by continent over the years
ggplot(data_long, aes(x = year, y = count_h1b, fill = Continent)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Continent, scales="free_y") +
  labs(title = "Total H1B Visas by Continent Over the Years",
       x = "Year", y = "Total Visas") +
  theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Calculate percentages for each continent per year
data_long <- data_long %>%
  left_join(total_h1b_by_year_long, by = "year") %>%
  mutate(percentage_of_total = count_h1b / Total_H1B_Visas)

# Plot percentage of total values by continent over the years
ggplot(data_long, aes(x = year, y = percentage_of_total, fill = Continent)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Continent, scales="free_y") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +
  labs(title = "Percentage of Total H1B Visas by Continent Over the Years",
       x = "Year", y = "Percentage of Total Visas") +
  theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))
```

>>>>>>> 5dcbcb76829b43c5323c8d54ece3b8995ca08211
